name       : libproxy
version    : 0.4.18
release    : 21
source     :
    - https://github.com/libproxy/libproxy/releases/download/0.4.18/libproxy-0.4.18.tar.xz : 69b5856e9ea42c38ac77e6b8c92ffc86a71d341fef74e77bef85f9cc6c47a4b1
homepage   : https://libproxy.github.io/libproxy/
license    : LGPL-2.1-or-later
component  : network.base
summary    : libproxy is a library that provides automatic proxy configuration management
description: |
    libproxy is a library that provides automatic proxy configuration management.
builddeps  :
    - pkgconfig(libnm)
rundeps    :
    - perl
setup      : |
    %cmake . \
        -DWITH_PYTHON2=OFF \
        -DPYTHON3_EXECUTABLE:FILEPATH=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
