name       : libproxy
version    : 0.4.17
release    : 19
source     :
    - https://github.com/libproxy/libproxy/releases/download/0.4.17/libproxy-0.4.17.tar.xz : bc89f842f654ee1985a31c0ba56dc7e2ce8044a0264ddca84e650f46cd7f8b05
homepage   : https://libproxy.github.io/libproxy/
license    : LGPL-2.1-or-later
component  : network.base
summary    : libproxy is a library that provides automatic proxy configuration management
description: |
    libproxy is a library that provides automatic proxy configuration management.
builddeps  :
    - pkgconfig(libnm)
setup      : |
    %cmake . \
        -DWITH_PYTHON2=OFF \
        -DPYTHON3_EXECUTABLE:FILEPATH=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
