name        : libproxy
version     : 0.4.11
release     : 2
source      :
    - https://libproxy.googlecode.com/files/libproxy-0.4.11.tar.gz : dc3f33de54163718f82b3e7c496a7de97f8862578414b8ecaad3cbfe4821864b
license     :
    - LGPL-2.1
summary     : libproxy is a library that provides automatic proxy configuration management.
component   : network.library
builddeps   :
    - pkgconfig(NetworkManager)
    - pkgconfig(mozjs185)
description : |
    libproxy is a library that provides automatic proxy configuration management.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
