name       : libproxy
version    : 0.4.15
release    : 8
source     :
    - https://github.com/libproxy/libproxy/releases/download/0.4.15/libproxy-0.4.15.tar.xz : 654db464120c9534654590b6683c7fa3887b3dad0ca1c4cd412af24fbfca6d4f
license    : LGPL-2.1
summary    : libproxy is a library that provides automatic proxy configuration management.
component  : network.library
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(mozjs-38)
description: |
    libproxy is a library that provides automatic proxy configuration management.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
