name       : libproxy
version    : 0.5.1
release    : 22
source     :
    - https://github.com/libproxy/libproxy/archive/refs/tags/0.5.1.tar.gz : 991109f122bffc6023f7f4b587b13cde4d2a416409cdda24cff6cf70dc283e83
homepage   : https://libproxy.github.io/libproxy/
license    : LGPL-2.1-or-later
component  : network.base
summary    : libproxy is a library that provides automatic proxy configuration management
description: |
    libproxy is a library that provides automatic proxy configuration management.
builddeps  :
    - pkgconfig(duktape)
    - pkgconfig(gi-docgen)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(vapigen)
    - pkgconfig(libnm)
    - pkgconfig(libcurl)
    - vala
patterns   :
    - docs :
      - /usr/share/doc
rundeps    :
    - perl
setup      : |
    %patch -p1 < $pkgfiles/fix-meson-includes.patch
    %meson_configure 
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
